### ISSUE TITLE
Progress ?

### ISSUE THREAD

**Issue by hmerk** [johnjore/Kala#1]
Hi John,
are you making any progress torwards first beta test releases ?

**Comment by johnjore** [comment]
Nope. Been busy with travels and other (ESP8266) projects. Logged a few bug reports that need fixing as soon as I can find some time. Feel free to help out...

**Comment by GunArm** [comment]
I'm looking to do something similar (but different ;) and I'm wondering how you intend to keep the panel display updated.  Will you be polling the rest api for state changes of the displayed item ui elements?  Or setting something up for Server Send Events?

Edit: Just saw your commentary post on openHAB community forums which says you've already added ui updating (at least on gauges etc), I did not see the enabling functionality in your RestService.cs...  Is that what Task GetUpdateAsync() does?  Except it is not used in openHAB.cs?

**Comment by johnjore** [comment]
UI updating for all the widgets has been there for a long time. There should be a thread that listens for incoming data and adds any new data to a queue for future processing. If the queue is empty another thread is created that processes the queue until empty. This way the listener thread hopefully does not drop any updates.

**Comment by johnjore** [comment]
Cycling back to this plugin and should hopefully find time to fix a few bugs and support for blinds.
